# References {-}
1. United Nations. (2024). Sustainable development goal 8: Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all. https://www.un.org/sustainabledevelopment/economic-growth/
2. United Nations. (2024). Sustainable development goal 16: Promote peaceful and inclusive societies, provide access to justice for all and build effective, accountable and inclusive institutions. https://www.un.org/sustainabledevelopment/peace-justice/
3. USAspending.gov. (2026). Department of Defense spending profile, fiscal year 2026. https://www.usaspending.gov/agency/department-of-defense?fy=2026
4. lements, B., Gupta, S., & Khamidova, S. (2021). Military spending in the post-pandemic era. Finance & Development, International Monetary Fund. https://www.imf.org/external/pubs/ft/fandd/2021/06/military-spending-in-the-post-pandemic-era-clements-gupta-khamidova.htm
5. Roser, M. (2013). Military personnel and spending. Our World in Data. https://ourworldindata.org/military-personnel-spending
CNN Politics. (2026, April 3). White House seeks massive increase in defense spending and looks to slash housing, social services and health care. https://www.cnn.com/2026/04/03/politics/white-house-budget-proposal-defense-spending-trump
6. National Guard Association of the United States. (2026). President proposes $1.5 trillion defense budget. https://www.ngaus.org/newsroom/president-proposes-15-trillion-defense-budget
7. Arms Control Association. (2026, March). U.S. defense spending rises by more than 17 percent. https://www.armscontrol.org/act/2026-03/news/us-defense-spending-rises-more-17-percent
8. Committee for a Responsible Federal Budget. (2026). $1.5 trillion military budget would add $5.8 trillion to debt over decade. https://www.crfb.org/blogs/15-trillion-military-budget-would-add-58-trillion-debt-over-decade
9. International Institute for Strategic Studies. (2026, February 24). The military balance 2026: Global defence spending. https://www.iiss.org/publications/the-military-balance/2026/
10. National Defense Magazine. (2026, January 29). Global defense spending to top $2.6 trillion in 2026. https://www.nationaldefensemagazine.org/articles/2026/1/29/global-defense-spending-to-top-2-6-trillion-in-2026
